<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Created by GNU Texinfo 6.8, https://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>try (chez-a-sync)</title>

<meta name="description" content="try (chez-a-sync)">
<meta name="keywords" content="try (chez-a-sync)">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<meta name="viewport" content="width=device-width,initial-scale=1">

<link href="index.html" rel="start" title="Top">
<link href="index.html" rel="up" title="Top">
<link href="meeting.html" rel="prev" title="meeting">
<style type="text/css">
<!--
a.copiable-anchor {visibility: hidden; text-decoration: none; line-height: 0em}
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
span:hover a.copiable-anchor {visibility: visible}
ul.no-bullet {list-style: none}
-->
</style>


</head>

<body lang="en">
<span id="try"></span><div class="header">
<p>
Previous: <a href="meeting.html" accesskey="p" rel="prev">meeting</a>, Up: <a href="index.html" accesskey="u" rel="up">chez-a-sync reference</a> &nbsp; </p>
</div>
<hr>
<h4 class="node-heading">try</h4>

<p>This (a-sync try) library file provides a &rsquo;try&rsquo; macro for dealing with
exceptions.
</p>
<dl class="def">
<dt id="index-_0028try"><span class="category">Syntax: </span><span><strong>(try</strong> <em>body0 body1 ... (except condition cond-clause0 cond-clause1 ...))</em><a href='#index-_0028try' class='copiable-anchor'> &para;</a></span></dt>
<dd><p>Try is a macro used in the implementation of the event loop provided
by this library, and is exported in case it is useful to users.  The
macro has two keywords, &rsquo;try&rsquo; and &rsquo;except&rsquo;.  It executes the body
clauses, and if an exception is raised by them passes control to the
&rsquo;except&rsquo; block with &rsquo;condition&rsquo; set to the condition which was raised.
The cond-clauses are then evaluated as if in a cond expression.  If a
cond test is found to be true, or there is none found to be true but
there is an else clause, then the relevant cond consequent or else
clause will be evaluated and returned.  If none of the cond tests in
the cond-clauses is found to be true and there is no else clause, the
exception condition will be re-raised as if by raise, for a
dynamically enclosing try form, guard form or with-exception-handler
form (if any) to handle.
</p>
<p>The return value of try, if there is no exception raised by the body
clauses or any exception raised is handled by a cond-clause, is the
value of the last expression of the body clauses or of the
cond-clause, as the case may be.
</p>
<p>This is similar to but not the same as the R6RS &rsquo;guard&rsquo; form.  The
guard form has the property that the cond tests and any cond
consequent or else clause are evaluated in the dynamic environment of
the call to &rsquo;guard&rsquo;, and if no cond test is found to be true and there
is no else clause, there is a return to the dynamic environment in
which the exception arose for the exception condition to be re-raised
with raise-continuable (the use of raise-continuable is to allow
continuable exceptions to propagate successfully through the &rsquo;guard&rsquo;
form).  However, this can result in triggering multiple dynamic
unwinds and rewinds.  As mentioned, the &rsquo;try&rsquo; form always re-raises
with &rsquo;raise&rsquo; (so in effect converting any continuable exception to a
non-continuable one).  Furthermore it only exits the dynamic
environment in which the exception occurred once.  Prior to version
0.24 of this library it did this by evaluating the cond tests, and any
cond consequent or else clause, or re-raising the exception, in the
dynamic environment of the original call to &rsquo;try&rsquo;.  From version 0.24
the cond tests are evaluated, and any re-raising of the exception
occurs, in the dynamic environment in which the exception arose, and
only the cond consequent (upon a test succeeding) or else clause is
evaluated in the dynamic environment of the call to &rsquo;try&rsquo;.  This
change is to avoid losing relevant debugging information should the
exception be re-raised, but in the highly unlikely event that user
code which applies this macro has a cond test which accesses parameter
values set by parameterize in the &rsquo;try&rsquo; body clauses, it could change
the behavior of the cond test.  If so, checkout try.ss for version
0.23 and use that (and have a little less debugability): either
version of try.ss will work fine with this library.
</p>
<p>Put another way, the &rsquo;try&rsquo; macro behaves like a conventional stack
unwinding exception implementation.  &rsquo;guard&rsquo; does not necessarily do
so.
</p>
<p>Continuable exceptions with generalised handling forms such as &rsquo;guard&rsquo;
are generally to be avoided, as they may break any intermediate
resource management which uses rethrows or dynamic winds.  Continuable
exceptions are also usually unsuitable for use with asynchronous event
handlers, which is why the &rsquo;try&rsquo; form is used in the implementation of
the event loop provided by this library.  But for cases where that is
not true and you know what you are doing, you can use &rsquo;guard&rsquo; instead
of &rsquo;try&rsquo; for maintaining continuable exceptions as continuable.
</p>
<p>The &rsquo;try&rsquo; macro is first available in version 0.3 of this library.
</p>
<p>Here is an example of the use of try:
</p><div class="example">
<pre class="example">(display (try (display &quot;In outer try form\n&quot;)
	      (try (display &quot;In inner try form\n&quot;)
		   (raise 'five)
		   (except c
			   [(eq? c 'six) 6]))
	      (except c
		      [(eq? c 'five) 5])))
</pre></div>
</dd></dl>

<hr>
<div class="header">
<p>
Previous: <a href="meeting.html">meeting</a>, Up: <a href="index.html">chez-a-sync reference</a> &nbsp; </p>
</div>



</body>
</html>
